Update config.yml

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -21,9 +21,20 @@ jobs:
             if [ -n "$changed_files" ]; then
               echo "Changes detected in ./docs/standard_tables folder."
               echo "$changed_files" | while read -r file; do
-                if ! awk -F '|' 'NR>2 { if ($3 !~ /^[[:space:]]*(True|False)[[:space:]]*$/) exit 1; if ($4 !~ /^[[:space:]]*[1-4](,[[:space:]]*[1-4])*[[:space:]]*$/) exit 1; if ($5 !~ /^[[:space:]]*(True|False)[[:space:]]*$/) exit 1 }' "$file"; then
-                  echo "ERROR: $file does not contain a valid Markdown table with the required format."
-                  exit 1
+                if ! awk -F '|' 'NR>2 {
+                    if ($3 !~ /^[[:space:]]*(True|False)[[:space:]]*$/) {
+                        echo "ERROR: $file - The value in the \"Is the deviation reasonable?\" column must be either \"True\" or \"False\"."
+                        exit 1
+                    } else if ($4 !~ /^[[:space:]]*[1-4](,[[:space:]]*[1-4])*[[:space:]]*$/) {
+                        echo "ERROR: $file - The value in the \"Error Types\" column must be a comma-separated list of numbers from 1 to 4."
+                        exit 1
+                    } else if ($5 !~ /^[[:space:]]*(True|False)[[:space:]]*$/) {
+                        echo "ERROR: $file - The value in the \"Display Free text question?\" column must be either \"True\" or \"False\"."
+                        exit 1
+                    }
+                }' "$file"; then
+                    echo "ERROR: $file does not contain a valid Markdown table with the required format."
+                    exit 1
                 fi
               done
             else
